Repository wecode-bootcamp-korea/39-backend-westagram-1, pull requests merged in 2022-11, with the labels that each got.

#3 [오현상-team1] Assignment 1 : Express API - 초기 환경 세팅
  HYUNSANG_OH/.env.sample
  HYUNSANG_OH/.gitignore
  HYUNSANG_OH/app.js
  HYUNSANG_OH/package-lock.json
  HYUNSANG_OH/package.json
Labels: 완료

#2 [지송현] Assignment 1: Express API - 초기 환경 세팅
  songhyun/.env.sample
  songhyun/.gitignore
  songhyun/app.js
  songhyun/package-lock.json
  songhyun/package.json
Labels: 완료

#5 [이명석] Assignment 1: Express API - 초기 환경 세팅
  myeongseok/.env.sample
  myeongseok/.gitignore
  myeongseok/.preettierrc
  myeongseok/app.js
  myeongseok/package-lock.json
  myeongseok/package.json
Labels: 완료

#6 [오현상-team1] Assignment2 : Express API - 유저 회원가입 하기
  .gitignore
  HYUNSANG_OH/.gitignore
  HYUNSANG_OH/app.js
  HYUNSANG_OH/db/migrations/20221102045526_users.sql
  HYUNSANG_OH/package-lock.json
  HYUNSANG_OH/package.json
Labels: 완료

#8 [오현상-team1] Assignment3 : Express API - 게시글 등록하기
  HYUNSANG_OH/app.js
  HYUNSANG_OH/db/migrations/20221102053646_posts.sql
Labels: 완료

#7 [이명석] Assignment 2: Express API - 유저 회원가입 하기
  myeongseok/app.js
  myeongseok/db/migrations/20221101235621_users.sql
Labels: 완료

#9 [지송현] Assignment 2 | Westagram Backend Project - 유저 회원가입 하기
  songhyun/app.js
  songhyun/package-lock.json
  songhyun/package.json
Labels: 완료

#11 [이명석] Assignment 3: Express API - CRUD (게시물 등록하기)
  myeongseok/app.js
  myeongseok/db/migrations/20221103071631_create_posts_table.sql
Labels: 완료

#13 [이명석] Assignment 4: Express API - CRUD (전체 게시글 조회하기)
  myeongseok/app.js
Labels: 완료

#16 [박상욱-team1] Assignment1 : Express API - 초기 환경 세팅
  sanguk/.env.sample
  sanguk/.gitignore
  sanguk/app.js
  sanguk/db/migrations/20221103072455_create_authors_table.sql
  sanguk/db/migrations/20221103072511_create_books_table.sql
  sanguk/db/migrations/20221103072556_create_books_authors_table.sql
  sanguk/package-lock.json
  sanguk/package.json
Labels: 완료

#14 [이은영-team1] Assignment2 : Express API - 유저 회원가입 하기
  eunyoung/.env.sample
  eunyoung/.gitignore
  eunyoung/app.js
  eunyoung/db/migrations/20221103045428_create_users_table.sql
  eunyoung/package-lock.json
  eunyoung/package.json
Labels: 완료

#18 [이은영-team1] Assignment3 : Express API - 게시글 등록하기
  eunyoung/.gitignore
  eunyoung/app.js
  eunyoung/db/migrations/20221103112800_create_posts_table.sql
Labels: 완료

#21 [이은영] Assignment4: Express API - 전체 게시글 조회하기
  eunyoung/app.js
  eunyoung/db/migrations/20221103045428_create_users_table.sql
  eunyoung/db/migrations/20221103112800_create_posts_table.sql
Labels: 완료

#19 [이명석] Assignment 5: Express API - CRUD (유저 게시글 조회하기)
  myeongseok/app.js
  myeongseok/package-lock.json
  myeongseok/package.json
Labels: 완료

#23 [김한솔] Assignment 1: Westagram Backend Project - Express 초기 환경세팅 요청
  Hansol_kim/app.js
  Hansol_kim/package-lock.json
  Hansol_kim/package.json
Labels: 완료

#25 [박상욱-team1] Assignment2 : Express API - 유저 회원가입 하기
  sanguk/app.js
  sanguk/db/migrations/20221103072455_create_authors_table.sql
  sanguk/db/migrations/20221103072511_create_books_table.sql
  sanguk/db/migrations/20221103072556_create_books_authors_table.sql
  sanguk/db/migrations/20221104065543_users.sql
Labels: 완료

#17 [오현상-team1] Assignment 5~8 : Express API - 전체 게시글 조회하기]
  HYUNSANG_OH/app.js
  HYUNSANG_OH/db/migrations/20221103082109_likes.sql
  HYUNSANG_OH/package-lock.json
  HYUNSANG_OH/package.json
Labels: 완료

#27 [이명석] Assignment 7: Express API - CRUD (유저 게시글 삭제하기)
  myeongseok/app.js
Labels: 완료

#24 [이명석] Assignment 6: Express API - CRUD (유저 게시글 수정하기)
  myeongseok/app.js
Labels: 멘토 리뷰 요청, 수정 요청

#28 [이명석] Assignment 8: Express API - CRUD (좋아요 누르기)
  myeongseok/app.js
  myeongseok/db/migrations/20221104134440_likes.sql
  myeongseok/db/migrations/20221104143357_update_posts_table.sql
  myeongseok/db/migrations/20221106070152_update_posts_table_uniquekeydelete.sql
  myeongseok/db/migrations/20221106070802_update_posts_table_foreignkey.sql
  myeongseok/db/migrations/20221106072024_update_likes_table_deleteuniquekey.sql
  myeongseok/db/migrations/20221106072858_update_likes_table_addforeignkey.sql
  myeongseok/db/migrations/20221107072412_update_posts_table_namingConvention.sql
  myeongseok/db/migrations/20221108081657_update_likes_table_addUniqueConstraint.sql
  myeongseok/package-lock.json
  myeongseok/package.json
Labels: 멘토 리뷰 요청

#33 [지송현] authentication1
  songhyun/app.js
  songhyun/package-lock.json
  songhyun/package.json
Labels: 완료

#26 [지송현] 과제4~8
  songhyun/.gitignore
  songhyun/app.js
  songhyun/db/migrations/20221102061711_users.sql
  songhyun/db/migrations/20221102070148_posts.sql
  songhyun/db/migrations/20221104035249_likes.sql
  songhyun/db/migrations/20221109094512_column_update.sql
Labels: 완료

#34 [오현상] Authentication(인증/인가) 1~3
  HYUNSANG_OH/app.js
  HYUNSANG_OH/package-lock.json
  HYUNSANG_OH/package.json
Labels: 완료
